### ISSUE TITLE
Cannot read property 'define' of undefined

### ISSUE THREAD

**Issue by matheusrocha89** [chrisdavies/rlite#24]
When I try to use the lib I get this error: 
```
Uncaught TypeError: Cannot read property 'define' of undefined
    at routes (index.js:723)
    at Object.<anonymous> (index.js:732)
    at __webpack_require__ (index.js:20)
    at Object.<anonymous> (index.js:623)
    at __webpack_require__ (index.js:20)
    at Object.<anonymous> (index.js:53)
    at __webpack_require__ (index.js:20)
    at index.js:40
    at index.js:43
```
Basically it's on this line:
` var define = root.define;`

It's trying to get `define` of `root` but `root` is `undefined`

**Comment by chrisdavies** [comment]
How are you running it?

Here's a working example, using the latest version of Rlite:

http://jsbin.com/vitazit/edit?html,js,output

**Comment by chrisdavies** [comment]
Ah. Just noticed the webpack bit. I was pretty sleepy when I first read / responded to this. We use Webpack with Rlite 1.x, but I haven't been using Webpack with 2.x. I'll get it fixed.

**Comment by matheusrocha89** [comment]
Thanks @chrisdavies
