### ISSUE TITLE
Possible wildcard match bug

### ISSUE THREAD

**Issue by silverwind** [chrisdavies/rlite#30]
Not sure if this counts as a bug, but

````js
(require('.')(() => console.log('404'), {
  '/foo/*bar': () => console.log('1'),
  '/foo/:baz/qux': () => console.log('2'),
}))('/foo/something');
````
logs `404`. When I comment the second route, it goes to the first as expected.

**Comment by chrisdavies** [comment]
It's not a bug. You'd need to do `/foo/something/qux` to match the second route.

**Comment by silverwind** [comment]
Note sure I follow. I'd like this to go to the wildcard route as it's the only one that matches.

**Comment by silverwind** [comment]
Thought it's a easy workaround in my case by change the first route to `/foo/:bar` as I don't expect any slashes in `:bar`.

**Comment by chrisdavies** [comment]
Ah. I see what you're saying. I misunderstood, sorry! I'll have a look into it, but I like your workaround for the time-being!

**Comment by chrisdavies** [comment]
Thanks for reporting this. It was a stupid bug. It's covered by regression tests now, so it shouldn't happen again!

**Comment by silverwind** [comment]
Thanks again for the quick turnaround. I really like this little router!

**Comment by chrisdavies** [comment]
:)
