### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by David263** [chrisdavies/rlite#33]
Dumb question: what is routing? I read the README and I'm still mystified.

**Comment by chrisdavies** [comment]
Yah. I was, too, when I first got into web-dev, as I'd only heard the term when referring to network routers. In web-dev, a router is the code that takes a URL `/foo/bar/baz` and maps it to some code that will run when the browser navigates to that URL (or on the server side, when a user requests a URL). So, a router provides a way of saying, "when url /foo is requested, run the fooBar() function, but when url /baz is hit, run the fooBaz() function".
