### ISSUE TITLE
Can't load / use rlite

### ISSUE THREAD

**Issue by pwFoo** [chrisdavies/rlite#35]
Maybe related to #26 because I'm new with modules and just try to use it as "script"...

Loaded by 
```
<script src="https://cdn.rawgit.com/chrisdavies/rlite/d025c663/rlite.min.js"></script>
```
I get following error
```
Uncaught ReferenceError: rlite is not defined
```

And also tested as module
```
<script type="module" src="https://cdn.rawgit.com/chrisdavies/rlite/d025c663/rlite.min.js"></script>
```
with error:
```
Uncaught ReferenceError: rlite is not defined
rlite.js:15 Uncaught TypeError: Cannot set property 'Rlite' of undefined
```

How to load rlite the right way in a html file as js?

**Comment by pwFoo** [comment]
@chrisdavies 
Could you help me how to use `rlite`  the "old" js / script tag way?
Errors see above.

**Comment by pwFoo** [comment]
It works loaded as script without `type=module` and as `Rlite`,

But looks like it doesn't work "out of the box", because there is no route handler (for example routes like `/inbox` or `/test?param=val`) and no prevent default action.

**Comment by chrisdavies** [comment]
Yup. `Rlite` needs to be capitalized. Other than that, the examples in the readme should just work for you out of the box.
