### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by dariocravero** [chrisdavies/rlite#4]
Hi @chrisdavies, have you published the package to npm already? Unfortunately [rlite](https://www.npmjs.com/search?q=rlite) seems to be taken. It will make it much easier to handle it as a dependency... Thanks :) Darío

**Comment by chrisdavies** [comment]
Oh, lame that it's taken! I have not published to npm yet. Will do this evening.

**Comment by chrisdavies** [comment]
Sorry I took so long to do this.

Here's the link:
https://www.npmjs.com/package/rlite-router

**Comment by jesusprubio** [comment]
:)

**Comment by dariocravero** [comment]
Class :) Thanks!
